### PR TITLE
RC2 working branch

### PR DESCRIPTION
**Pull request by orogvany**
This is a branch that collects all current PRs while they are under review.  The review/merge for them should happen under their respective PRs.

This just gives a place to test the current latest fixpack.  RC2 will be released from develop branch.

### CODE REVIEW

**Comment by honeycrypto** [comment]
Now synchronisation stuck on this and cannot add blocks 681201-681400 with `Block votes are invalid` error: 
```
INFO     SemuxSync        Block [number = 681198, view = 0, hash = d8a621521aedf44286d1f5eee8238678498c8ab58d95f23c6b8c215fb8de811d, # txs = 0, # votes = 15]
INFO     SemuxSync        Block [number = 681199, view = 1, hash = d5ffa18a5e49a82381e592b0fb4101873d2073b0c8171a655924124c060de048, # txs = 0, # votes = 15]
INFO     SemuxSync        Block [number = 681200, view = 1, hash = b219cea5f80beda35a17878cb87ef5579586282351b12578c4500506dbf48078, # txs = 0, # votes = 15]
WARN     SemuxSync        Block votes are invalid
INFO     SemuxSync        Invalid block from 188.166.67.185:5161
WARN     SemuxSync        Block votes are invalid
...
```

**Comment by orogvany** [comment]
Hm. As you can see there are 0 changes to block voting validation in this change.  Can you try reconnecting as you may have a bad peer.  Else I can try resyncing testnet and attach debugger. 

Thanks for testing!

**Comment by orogvany** [comment]
Ah. May be due to adding the logevents for rc2?  I think there may have been some other changes already merged in for rc2 that someone else reviewed.  But will try resyncing testnet and seeing actual error

**Comment by honeycrypto** [comment]
Maybe that's due to bad votes of one validator who continued forging blocks and signalling for VM activation even after activation?

**Comment by orogvany** [comment]
found issue, and should be all merged in for testing again.

**Comment by honeycrypto** [comment]
yes, now synchronisation works from block 0 till the best height. I see this in the log: `Entered new_height: height = 751639, # validators = 23` - won't it cause a problem once we'll unfreeze the network? `getNumberOfValidators` will return 15 at this block heigh, but we already have more than maximum allowed number of validators before next adjustment at block xxx800

**Comment by orogvany** [comment]
Ok, merged in the fix for # of validators

**Comment by orogvany** [comment]
committing this as it includes other minor fixes for RC2

**Pull request merged**
