### PR TITLE
API: divide APIs into groups

### PR DESCRIPTION
**Pull request by semuxgo**
## Description

This PR assigns endpoints to different categories, which include
- Account - account related APIs
- Delegate - delegate or validator related APIs
- Blockchain - block or transaction related APIs
- Node - node information
- Wallet - APIs that require the wallet
- Tool - unity functions

Additional changes are also included:
- Replaced `/syncing` with `/syncing-status`;
- Replaced `/call` with `/local-call`;
- Replaced `/transaction/raw` with `/broadcast-raw-transaction`;
- Deprecated `POST /account` and `DELETE /account`;
- Added `/create-account` and `/delete-account`;
- Added `/local-create`.

## Test Plan

Existing tests

## Related issues and/or PRs

N/A

### CODE REVIEW

**Comment by orogvany** [comment]
Maybe consider taking method 'safety' into consideration to better support what uses local wallet and what is gneric.  Current public apis have to whitelist/blacklist based on which they choose that can be public

**Comment by orogvany** [comment]
Or make 'local wallet' only API separate port/config option to aid in spinning up a consistent public facing api

**Comment by semuxgo** [comment]
Good point. I briefly looked at the HTTP method types being used. 99% of the GET methods are safe to be exposed to public.

If we're okay with the following definition:
- GET methods don't change the state of this node ~or the network~;
- POST methods do,

we can then add a flag to allow users to disable POST methods if they want to make a public API.

**Comment by orogvany** [comment]
Hm. I don't think submit raw tx can be a GET due to url length?

**Comment by semuxgo** [comment]
Bumped the HTTP request size limits. Commit: 51fb2c186120785202d6541ecdfb50e714029bb9

Tested, working with both Java Client and Chrome.

**Comment by orogvany** [comment]
Ah. Ok. Thanks

**Pull request merged**
