### PR TITLE
Refactor VM-related API endpoints

### PR DESCRIPTION
**Pull request by semuxgo**
- Remove the block and gas info from the TransactionType and BlockType

### CODE REVIEW

**Comment by orogvany** [comment]
Oh. Wip, nevermind me

**Comment by semuxgo** [comment]
Good point, but I'd rather keep these derivative information separate and keep endpoints more independent.

**Comment by orogvany** [comment]
Block explorers and chain analysis tools now lose ability to display or use gas provided versus gas used, right?  

This is going to get more problematic when we get into internal transactions.

Currently I have a strong suspecion that if you use a VM call to send funds to an exchange that the funds will not be counted, and sem lost.

**Comment by semuxgo** [comment]
@orogvany I added the `/transaction-receipt` endpoint, similar to the Ethereum's web3 API.

**Comment by semuxgo** [comment]
TODO: update the database in regards to how transaction results are stored.

**Comment by orogvany** [comment]
Ok that makes sense. As long as transaction receipt covers gas, gas price, gas used, results/logs

We still do need to figure out the problem for exchanges missing out on call type requests. If even just in documentation.  Not sure how eth based exchanges handle it, if at all.

**Pull request merged**
