### PR TITLE
Consensus: change the block rewards

### PR DESCRIPTION
**Pull request by semuxgo**
See the proposal at https://github.com/semuxproject/RFPs/blob/master/proposals/002/honeycrypto.md

### CODE REVIEW

**Comment by semuxgo** [comment]
@orogvany 22m + 10m - delegate registraiton fees.

**Comment by orogvany** [comment]
ile '/home/travis/build/semuxproject/semux-core/src/main/java/org/semux/config/AbstractConfig.java' has not been previously formatted.  

Please fix.  I am ok with this change.  I am not sure this distribution works past this next Dec 2019 3->2 reduction (8 years until 0 sem rewarded seems odd) is ok, but the reduction for 3->2 in Dec 2019 at block 2 million is agreeable

**Comment by phash** [comment]
I think we should never go to 0.
0.2 SEM should be rewarded always to compensate lost coins.

But the rest is agreeable

**Comment by honeycrypto** [comment]
@phash it will go to 0 only in 13 years from now. Don't forget that even now Semux supports 5000 TXs per block, with the 0.005 SEM fee that's up to 25 SEM per block of fees. As we want to put our efforts on dapp market and create use cases for business, the rise of real transactions made by consummers in Semux blockchain is imminent. If after 13 years there will be only few transactions, then we'll have to admit that the project has failed and there is not much sense to have those 0.2 sem per block rewards.

**Pull request merged**
