### PR TITLE
Re-enable HD wallet

### PR DESCRIPTION
**Pull request by semuxgo**
Credit to @orogvany 

- Set the hd passphrase to empty
- Use fixed schme: SLIP10, English, Mainnet
- Optimize UI/UX
- Encrypt the mnemonic phrase and account index

### CODE REVIEW

**Comment by semuxgo** [comment]
I'd like to go with `SLIP-10` for now, as it's well tested and supported by trezor? The wallet stores the raw mnemonic phrase. We can derive keys based on any scheme of user choice in the future, for instance BIP32-ED25519 for Ledger support.

**Comment by orogvany** [comment]
I thought slip-10 was not the one trezor used.  Thought they used the cardano one?

**Comment by orogvany** [comment]
Oh. Slip-10 is trez and cardano is ledger?

**Comment by orogvany** [comment]
So depends on which one we want to Target.  Trez accepts pull requests, ledger is closed source?  Or maybe I have backwards

**Comment by semuxgo** [comment]
@orogvany Here is the reference to Trezor, https://github.com/trezor/trezor-firmware/tree/master/core/docs/coins. Would appreciate it if you can double check.

**Pull request merged**
